services:
  server:
    build: ./server
    container_name: carbonquest-server
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/carbonquest
      - SECRET_TOKEN_KEY=superUltraMegaSecretKey123
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - carbonquest-network

  mongodb:
    image: mongo:6.0
    container_name: carbonquest-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - carbonquest-network

networks:
  carbonquest-network:
    driver: bridge

volumes:
  mongodb_data:
